# wrangler.toml

name = "magnet-rss"
main = "src/index.js"
compatibility_date = "2025-07-12"

routes = [
    { pattern = "magnet.mc.rabbithouse31.natsuki.cloud", custom_domain = true }
]

[[kv_namespaces]]
binding = "MAGNET_KV"
id = "3faff10be5fa410a9fc95033feee93a3"

[vars]
MAGNET_RSS_KEY = "" # 占位符
