# wrangler.toml

name = "magnet-rss-worker"
main = "src/index.js"
compatibility_date = "2023-12-01"

routes = [
    { pattern = "magnet.mc.rabbithouse31.natsuki.cloud/*", custom_domain = true }
]

[[kv_namespaces]]
binding = "MAGNET_KV"
id = "3faff10be5fa410a9fc95033feee93a3"

# ✅ 新增：使用 [vars] 来声明环境变量
# MAGNET_RSS_KEY 是在代码中访问的变量名 (env.MAGNET_RSS_KEY)
# 实际值需要在 Cloudflare Dashboard 中配置
[vars]
MAGNET_RSS_KEY = "" # 这里的值只是一个占位符，实际值在Dashboard设置
